###


get http://localhost:3333/customerList 


###

post http://localhost:3333/customerList 
Content-Type: application/json

{
    "fname":"Swamy",
    "mobileNo":987654321
}


###

delete http://localhost:3333/customerList/65d34de345e70cd18fc6eba1 



###

get http://localhost:3333/customerList/65d49d96e1310634fc38e51b


###

get http://localhost:3333/empList 


###


post http://localhost:3333/empList 
Content-Type: application/json

{
    "newName":"Axel",
    "newMob":123456,
    "newEmail":"abc@gmail.com",
    "newSalary":50000,
    "newCity":"Mumbai",
    "newAddress":"Kolkata"

}

###



delete http://localhost:3333/empList/65d82fc814a03e8cf75ef329 

###

get http://localhost:3333/studentList





###

post http://localhost:3333/studentList
Content-Type: application/json

{
    "fullName":"Abhisar",
    "mobileNo":325696445554,
    "emailId":"test@gmail.com",
    "edu":{"school":"Vibgyor School","college":"Jupiter College","graduation":"MCA"},
    "skill":{"ui":"HTML,CSS,JavaScript","backend":"Node Js","database":"MongoDB"},
    "fullAddress":"Marathahalli,Bangalore"
}


###

delete http://localhost:3333/studentList/65d894c50f4ec906dfb79a02



###


get http://localhost:3333/studentList/65d8985a66103c1113917509



###

post http://localhost:1111/auth
Content-Type: application/json

{
    "email":"admin1@gmail.com",
    "password":"12345"
}
